MediaServer: Improve error handling for replay file operations
Ignore non-fatal errors when reading video data with ffprobe

Ignore permission errors when watching directories, since watching a
drive root can lead to permission errors from system directories like
"Recovery" and "System Volume Information". Still not sure why those
errors don't occur consistently; it seemd to have something to do with
how early the watcher is closed. Example error:

```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat
'C:\Users\Stream\OBS\NYCFB\OBS-Studio\bin\64bit\root\Recording\Recovery'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError
(C:\Users\Stream\git\detocs\node_modules\chokidar\index.js:629:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError
(C:\Users\Stream\git\detocs\node_modules\chokidar\lib\nodefs-handler.js:302:43)
    at ReaddirpStream.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
{
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path:
'C:\\Users\\Stream\\OBS\\NYCFB\\OBS-Studio\\bin\\64bit\\root\\Recording\\Recovery'
}
```